### ISSUE TITLE
Katselmointi

### ISSUE THREAD

**Issue by Jakousa** [Sendouc/sendou-ink#2]
# Katselmointi

### Mitä tein

* 28.7.2019 klo ~15:05

* Käytin sovellusta kirjautumatta
  * Tein planin, tallensin sen png + json. Latasin planin jsonista.
  * Katsoin muiden buildeja ja rankingejä.

* Kirjauduin
  * Lisäsin buildin, editoin sitä. Poistin sen.

### Kokemus

* README voisi sisältää enemmän kuvausta mikä palvelu on.

* Planin teko hajoaa jos piirrät kuvaa jonka jälkeen menet muulle sivulle ja palaat plans sivulle.

* Esimerkillinen palvelu. Löysin koko läpikäynnillä vain yhden ongelman.

## Koodi

* Tiedostot hyvin nimettyjä.

* Frontin komponentit ehkä hieman kummallisesti kansioitu. Esimerkiksi components kansion alikansiot voisi nimetä paremmin.

* Kaikki kolme tiedostoa BuildCollection.js, Build.js ja AbilityButtons.js alkavat samalla import matolla. Kaikki ikonit / nimet / etc voinee yhdistää toisessa tiedostossa ja hakea sen yhden tiedoston komponentteja varten.

* Tiedoston AbilityButtons.js return näyttää myös siltä että voisit säästää rivejä käymällä listaa läpi.

* Paikoitellen returniin on laitettu paljon logiikkaa. Esimerkiksi https://github.com/Sendouc/sendou-ink/blob/b2070fce5ccbf8df2169443ae7420a0246eaf76e/react-ui/src/components/SoloLadder/BuildTab.js on hieman ensisilmäyksellä monimutkainen loitsu "!user || user.discord_id !== userViewed.discord_id || data.searchForBuilds.length >= 100" jonka kaverina on "data.searchForBuilds.length >= 100 && user && user.discord_id === userViewed.discord_id".

* Toisaalta taas samassa tiedostossa seuraavalla rivillä showForm on selkeä.

* https://github.com/Sendouc/sendou-ink/blob/b2070fce5ccbf8df2169443ae7420a0246eaf76e/index.js#L17 portti kannattaa laittaa riippumaan samassa tiedostossa sijaitsevasta PORTista.

## Kokonaisuus

* Ongelmia piti hakemalla hakea, jatka samaan malliin!

* Työstä huomaa aiheen olevan lähellä tekijää ja laatu on myös sen mukaista.

🦑 / 🚸

**Comment by Jakousa** [comment]
Ihailin vielä sivua ja huomasin että voisit saada sivustolle hieman lisää käyttäjäystävällisyyttä tutustumalla https://reactjs.org/docs/code-splitting.html kautta React.lazy ja suspenseen. Tällä hetkellä tuo 5MB mötikkä javascriptiä tulee välittömästi vaikka menisi yksinkertaiselle etusivulle.

**Comment by Sendouc** [comment]
Kiitos hyvistä pointeista! Aika paljon ihan sellaista jota en tullut ajatelleeksi vielä. Kirjoitan parhaillani aika isoa osaa tuosta frontista uusiksi joten pidän mielessä nämä asiat sivuston tulevaisuutta ajatellen.
