### ISSUE TITLE
Date and time not using localized format in some areas

### ISSUE THREAD

**Issue by Walavouchey** [Sendouc/sendou-ink#23]
Here are the ones i've found.

In Tournament Results page (below tournament title)
![Greek Tourmanents page](https://wala.s-ul.eu/OTKBBMVh.png)

In Calendar page (below tournament title)
![Spanish Calendar page](https://wala.s-ul.eu/nJUUDHoc.png)

In Free Agents page (top left of each card)
![Swedish Free Agents page](https://wala.s-ul.eu/kRG8nbQO.png)

**Comment by Sendouc** [comment]
Thanks! Fixed in the latest version.
