### ISSUE TITLE
More freedom for posters in calendar

### ISSUE THREAD

**Issue by cYuza** [Sendouc/sendou-ink#33]
https://twitter.com/TobyBaratta/status/1278954990317367297
Mainly referring to this, since it's uneditable after you posted it you can't include a registration link before opening registration
My idea is to give post rights to a permitted group (people who ask for it) so you can monitor it easily while still leaving the original posters freedom to edit the messages

Not sure how feasible it is to implement this (especially with the discord-posts), but the Calendar is the imo most underappreciated feature of sendou.ink

**Comment by Sendouc** [comment]
![Annotation 2020-07-03 185643](https://user-images.githubusercontent.com/38327916/86484500-0617fe80-bd5f-11ea-8ad5-e7d9e0503edf.png)
Actually editing is supported if you mean this!
