### ISSUE TITLE
Issue when refreshing the Map Planner

### ISSUE THREAD

**Issue by SporeCloud** [Sendouc/sendou-ink#42]
If the map/mode is kept unchanged from Reef SZ and the map is drawn on, in the event the page is refreshed then the image fails to load. However it is still possible to draw on it:

![image](https://user-images.githubusercontent.com/44228349/87854882-c92a3b00-c90c-11ea-9565-ac511167b13a.png)

**Comment by Sendouc** [comment]
Yeah this has been an issue since forever but haven't managed to figured out what is causing it. Luckily changing the map fixes it right away. Leaving this open for now in any case.

**Comment by Sendouc** [comment]
This is fixed in the new version that will be put to sendou.ink sometime in the future: https://sendou-ink-mono.vercel.app/plans
