### ISSUE TITLE
[Request] Was this build helpful? Hebrew translation and Clash.

### ISSUE THREAD

**Issue by shachar700** [Sendouc/sendou-ink#43]
**Was this build helpful?** (QoL improvement)
Something to make builds have a bit of a feedback would be to add counter of how many players that build helped them. (Like in articles or answers for technical support that ask in the end if the answer was helpful or not. could be anonymus, could be yes or no question, could be just counter or could be just how many people saw your build. Not something crucial but suggestion nonetheless.

**Hebrew translation**
I can help with trasnlating sendou.ink to Hebrew. I see the site has been translated to languages that Splatoon 2 does not support in translations to them so I'm offering my help with translating to another language. Just let me know what I need to do and I'll gladly help with the translations.

**Clash Blaster**
Something really minor. The clash blaster in the search bar and in map planner appears after Rapid pro deco. I assume you took it from Inkipedia which I put it there by accident. The order that appears in the game that is sorted by main is an order that usually shows from short to long range and then unique mechanic (like the blasters, burst fire, sloshers for example). The correct order of clash is actually after the Grim Blaster.
https://splatoon2.ink/data/locale/en.json

Kind regards,
Shahar

**Comment by Sendouc** [comment]
> Was this build helpful?

Hmm yeah I have been wondering about that I just don't know how qualified people are to rate up builds they don't have any knowledge of. Say compared to upvoting on Reddit where people are very qualified on voting on whether they like the content or not. If anything I'd implement downvoting so the meme builds go last but idk if that is a bit harsh.

> Hebrew translation

Sure thing DM me on Discord and we can get it started.

> Clash Blaster

Good catch! Will fix.

**Comment by Sendouc** [comment]
Will close for now as the first suggestion I don't think is something I'll implement this time and last one already got fixed. Including support for RTL languages is possible for future if there is some actual demand.
