### ISSUE TITLE
Update maplist queries to take the name of the maplist as an argument

### ISSUE THREAD

**Issue by LeptoFlare** [Sendouc/sendou-ink#7]
As of right now, the maplist queries send more data than nessecary.

Change the maplist query to take an optional `name: ` argument to return the specific maplist.
![image](https://user-images.githubusercontent.com/47790183/83339966-0aa15100-a2a1-11ea-8e95-479eae554b41.png)

Additionally, add an optional `index: ` argument to return a maplist at a specific index.

For backwards compatibility, you can also just add a new query called `maplist` (vs `maplists`) to return a specific maplist.

**Comment by Sendouc** [comment]
`maplists` query now takes `name` as optional parameter

However I won't touch the query further for now as eventually I plan to allow people to make their own map lists on the site and with that the backend will also change quite a bit.
